function national=read_national_workbook(file)
% Read total.xlsx: age labels in column A, census years across row 1.
% Restrict the populated rectangle: this workbook has formatting to row 16375.
c=readcell(file,'Sheet','Sheet1','Range','A1:D22');
assert(isequal(size(c),[22 4]),'IV:NationalLayout', ...
    'Expected national age table in Sheet1!A1:D22.');
years=[2000 2010 2020];
assert(strcmp(string(c{1,1}),"year"),'IV:NationalLayout','Missing year header.');
for k=1:3
    assert(isnumeric(c{1,k+1}) && isequal(c{1,k+1},years(k)), ...
        'IV:NationalYears','National columns B:D must be 2000,2010,2020.');
end
labels=["0岁人口";"1-4岁人口(人)";"5-9岁人口(人)"; ...
    "10-14岁人口(人)";"15-19岁人口(人)";"20-24岁人口(人)"; ...
    "25-29岁人口(人)";"30-34岁人口(人)";"35-39岁人口(人)"; ...
    "40-44岁人口(人)";"45-49岁人口(人)";"50-54岁人口(人)"; ...
    "55-59岁人口(人)";"60-64岁口(人)";"65-69岁人口(人)"; ...
    "70-74岁人口(人)";"75-79岁人口(人)";"80-84岁人口(人)"; ...
    "85岁及以上人口(人)"];
assert(isequal(string(c(4:22,1)),labels),'IV:NationalLabels', ...
    'National age labels/order changed. Check the import mapping.');
p=zeros(19,3);
for a=1:19
    for k=1:3
        v=c{a+3,k+1};
        assert(isnumeric(v) && isscalar(v) && isfinite(v) && v>=0, ...
            'IV:NationalCount','Invalid national count at Excel row %d, column %d.',a+3,k+1);
        p(a,k)=v;
    end
end
p=[sum(p(1:2,:),1);p(3:end,:)];
national=table(repelem(years',18),repmat((0:5:85)',3,1),p(:), ...
    'VariableNames',{'year','age_start','population'});
end
