function [city,cityNames]=read_city_workbook(file,confirm4549BothSexes)
% Import iv-essential data.xlsx without changing the source workbook.
% Set confirm4549BothSexes=true ONLY after verifying the mislabeled column.
if nargin<2, confirm4549BothSexes=false; end
t=readtable(file,'Sheet','Sheet1','VariableNamingRule','preserve');
expected=["地区名称","城市编码","year","平均年龄","劳动平均年龄", ...
    "0岁人口","1-4岁人口(人)","5-9岁人口(人)","10-14岁人口(人)", ...
    "15-19岁人口(人)","20-24岁人口(人)","25-29岁人口(人)", ...
    "30-34岁人口(人)","35-39岁人口(人)","40-44岁人口(人)", ...
    "45-49岁女性人口(人)","50-54岁人口(人)","55-59岁人口(人)", ...
    "60-64岁口(人)","65-69岁人口(人)","70-74岁人口(人)", ...
    "75-79岁人口(人)","80-84岁人口(人)","85岁及以上人口(人)"];
actual=string(t.Properties.VariableNames);
% Accept a corrected both-sex header without an override.
if numel(actual)==24 && actual(16)=="45-49岁人口(人)"
    expected(16)=actual(16);
    confirm4549BothSexes=true;
end
assert(isequal(actual,expected),'IV:WorkbookHeaders', ...
    'Workbook layout changed. Check headers before adapting the import.');
% The updated workbook appends three nationwide totals without city codes.
% Exclude ONLY explicitly named aggregate rows, never arbitrary missing IDs.
names=strtrim(string(t{:,1}));
aggregate=ismember(names,["合计","全国","总计"]);
fprintf('Excluded %d explicitly labeled aggregate rows.\n',sum(aggregate));
t=t(~aggregate,:);
ids=string(t{:,2});
assert(~any(ismissing(ids) | ids=="NaN" | strlength(strtrim(ids))==0), ...
    'IV:CityID','A nonaggregate row has no city ID.');
cityNames=unique(table(ids,string(t{:,1}), ...
    'VariableNames',{'city_id','city_name'}),'rows');
assert(numel(unique(cityNames.city_id))==height(cityNames), ...
    'IV:CityName','A city ID maps to more than one name.');
assert(isequal(confirm4549BothSexes,true),'IV:SexDefinition', ...
    ['Column 16 is labeled female population. Verify it is BOTH SEXES ', ...
    'before setting confirm4549BothSexes=true; otherwise supply corrected counts.']);
counts=t{:,6:24};
assert(isnumeric(counts) && all(isfinite(counts(:))) && all(counts(:)>=0), ...
    'IV:WorkbookCounts','All population cells must be finite nonnegative numbers.');
% 0 and 1-4 combine to 0-4. Remaining groups are 5-9,...,80-84,85+.
counts=[sum(counts(:,1:2),2),counts(:,3:end)];
n=height(t); ages=(0:5:85)';
city=table(repelem(string(t{:,2}),18),repelem(t{:,3},18), ...
    repmat(ages,n,1),reshape(counts.',[],1), ...
    'VariableNames',{'city_id','year','age_start','population'});
end
